[package]
name = "couch-cli"
version.workspace = true
edition.workspace = true
publish.workspace = true

[[bin]]
name = "couch"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
couch-manifests.workspace = true
couch-local-library.workspace = true
couch-runtime.workspace = true
couch-web-host.workspace = true
couch-platform.workspace = true
directories.workspace = true
serde_json.workspace = true
sha2.workspace = true
tokio.workspace = true

[dev-dependencies]
tempfile.workspace = true
